### ISSUE TITLE
More defaults

### ISSUE THREAD

**Issue by xeruf** [yoarch/timer#1]
Thanks for the handy tool!
Suggestion: Default to seconds, like other typical commands such as `sleep`.
I wanted to suggest adding support for repeating the timer, but apparently you have a separate script for that, idk why? https://github.com/yoarch/regal

**Comment by EgalitarianMonkey** [comment]
Hello @xeruf,
Indeed, seconds by default and a repeating option would be nice.
I am very busy in this moment but going to try to do it. If you want to help..
Thanks.

**Comment by EgalitarianMonkey** [comment]
Hello @xeruf,
I just implemented your proposals. Have a look at the README, test the code and tell me what you think.

**Comment by xeruf** [comment]
Thank you, seems good :)
Just one thing: I think the duration of the audio sound is interfering with the interval, so a 3s timer sometimes takes 4 or 5 seconds.
![image](https://user-images.githubusercontent.com/13354331/204038298-ec3c7f3a-b72e-4eec-9920-52ab4a5a16cd.png)

**Comment by EgalitarianMonkey** [comment]
Yes, I know :(
I can put in background but I get extra stdouts getting a worse appearance.
Do you think it would be better to be accurate on the time rather than the appearance ?

**Comment by xeruf** [comment]
can't you simply subtract the audio length?

**Comment by EgalitarianMonkey** [comment]
You can specify any custom audio files. It seems complicated to measure the audio file length.
I think the best would be to have it in background indeed.

**Comment by EgalitarianMonkey** [comment]
I finally put the audio play in background without extra output to get a real accurate regular timer.

**Comment by xeruf** [comment]
nice, thank you
getting audio length would have been quite easy with something like ffmpeg as well ;)

**Comment by EgalitarianMonkey** [comment]
Good to know. Thanks.
